services:
  - type: web
    name: cinenova-api
    runtime: docker
    rootDir: .
    dockerfilePath: ./infra/docker/api.Dockerfile
    dockerContext: .
    plan: free
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        sync: false
      - key: DIRECT_URL
        sync: false
      - key: REDIS_URL
        sync: false
      - key: JWT_SECRET
        generateValue: true
      - key: QR_TOKEN_SECRET
        generateValue: true
      - key: SERVICE_TOKEN_SECRET
        generateValue: true
      - key: AI_SERVICE_URL
        fromService:
          type: web
          name: cinenova-ai
          property: hostport
      - key: NEXT_PUBLIC_APP_URL
        value: https://cinenova.vercel.app
      - key: PAYMENT_PROVIDER
        value: mock
    healthCheckPath: /api/health/liveness

  - type: web
    name: cinenova-ai
    runtime: docker
    rootDir: .
    dockerfilePath: ./infra/docker/ai.Dockerfile
    dockerContext: .
    plan: free
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        sync: false
      - key: REDIS_URL
        sync: false
      - key: SERVICE_TOKEN_SECRET
        sync: false
      - key: LLM_PROVIDER
        value: gemini
      - key: GEMINI_API_KEY
        sync: false
    healthCheckPath: /healthz
